import { useEffect, useState, useMemo } from 'react';
import { useWallet } from '@cosmos-kit/react';
import { assets } from 'chain-registry';
import { AssetList, Asset } from '@chain-registry/types';

// import cosmwasm client generated with cosmwasm-ts-codegen
import { HackCw20QueryClient } from '../codegen/HackCw20.client';

import {
  Box,
  Divider,
  Grid,
  Heading,
  Text,
  Stack,
  Container,
  Link,
  Button,
  Flex,
  Icon,
  useColorMode,
  useColorModeValue
} from '@chakra-ui/react';
import { BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { dependencies, products } from '../config';

import { WalletStatus } from '@cosmos-kit/core';
import { Product, Dependency, WalletSection } from '../components';
import Head from 'next/head';
import Navbar from '../components/navbar';
import Layout from '../components/navbar';
import CsvProcessor from '../components/react/csvProcessor';


export default function Home() {

  return (
    <Layout>
      <Container maxW="5xl" py={10}>
        <Head>
          <title>Create Cosmos App</title>
          <meta name="description" content="Generated by create cosmos app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex justifyContent="end" mb={4}>
        </Flex>
        <Box textAlign="center">
          <CsvProcessor></CsvProcessor>
        </Box>
      </Container>
    </Layout>
  );
}
