[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.4"
pdqsort = "1.0.3"
serde = "1.0.144"
base64 = "0.13.0"

[dev-dependencies]
serde_json = "1.0.85"
