[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.4"
pdqsort = "1.0.3"
serde = { version="1.0.144", features=["derive"] }
base64 = "0.13.0"

[dev-dependencies]
serde-json-wasm = "0.4.1"
