/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface Config {
  merkle_root: string;
  owner: Addr;
}
export type ExecuteMsg = {
  set_sub_denom: {
    subdenom: string;
  };
} | {
  claim: {
    amount: Uint128;
    claimer_addr: string;
    proof: string;
  };
};
export type Uint128 = string;
export interface GetRootResponse {
  root: string;
}
export interface GetSubdenomResponse {
  subdenom: string;
}
export interface InstantiateMsg {
  merkle_root: string;
}
export type QueryMsg = {
  get_root: {};
} | {
  get_subdenom: {};
};